# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AFHS FFA Boosters
email: afhsffaalumni@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Apex Friendship High School FFA Boosteres
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.afhsffaboosters.com" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: APex Friendship FFA Alumni and Supporters
address_line: 1110 Heathwood Dairy Rd, Apex, NC 27502
telephone_number: 919.600.1509
fax_number: 111
company_email: afhsffaalumni@gmail.com
google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3240.0015069639694!2d-78.91311798774075!3d35.701580528739974!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89ac939c79c07b13%3A0xea46c04760484bc9!2sApex%20Friendship%20High%20School!5e0!3m2!1sen!2sus!4v1693495598166!5m2!1sen!2sus

# Social Link
facebook_link: http://www.facebook.com
twitter_link: http://www.twitter.com
linkedin_link: http://www.linkedin.com
googleplus_link: http://plus.google.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
